/**
 * Creates a sandbox from the "libretto-app" snapshot, starts the in-sandbox
 * server on :3000, and prints a public preview URL. Ctrl-C tears down.
 *
 * Required env: ANTHROPIC_API_KEY (server's libretto snapshot uses it).
 *
 * Usage:
 *   ANTHROPIC_API_KEY=sk-... npx tsx launch.ts
 */

import { readFileSync } from "node:fs";

import { Sandbox, SecretStore } from "@opencomputer/sdk/node";

const SNAPSHOT_NAME = "libretto-app";
const SECRET_STORE = "libretto-demo";
const APP_PORT = 3000;

async function main() {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY must be set");

  // Secrets-proxy quirk: sandbox egress only works when a SecretStore is
  // attached (and it has ≥1 entry). See run.ts for the full explanation.
  const stores = await SecretStore.list();
  let store = stores.find((s) => s.name === SECRET_STORE);
  if (!store) {
    console.log(`Creating secret store "${SECRET_STORE}" with egress *...`);
    store = await SecretStore.create({ name: SECRET_STORE, egressAllowlist: ["*"] });
  } else {
    await SecretStore.update(store.id, { egressAllowlist: ["*"] });
  }
  await SecretStore.setSecret(store.id, "LIBRETTO_DUMMY", "placeholder-to-register-proxy-session");

  console.log(`Launching sandbox from snapshot "${SNAPSHOT_NAME}"...`);
  const sandbox = await Sandbox.create({
    snapshot: SNAPSHOT_NAME,
    timeout: 0, // persistent; we kill explicitly on Ctrl-C
    envs: {
      ANTHROPIC_API_KEY: apiKey,
      // Keep Playwright/Chromium off the small tmpfs /dev/shm and /tmp —
      // write profile dirs, cache, everything to the data disk.
      TMPDIR: "/home/sandbox/tmp",
    },
    secretStore: SECRET_STORE,
    cpuCount: 4,
    memoryMB: 16384,
  });
  console.log(`  sandbox id: ${sandbox.sandboxId}`);

  // Per-boot setup (same as run.ts): /etc/hosts + Chromium NSS trust for the
  // OC egress-proxy CA. These are per-sandbox (CA is regenerated by the
  // worker), so they can't be baked into the snapshot.
  await sandbox.commands.run(
    "grep -q 'localhost' /etc/hosts || " +
      "(printf '127.0.0.1 localhost\\n::1 localhost\\n' | sudo tee -a /etc/hosts)",
  );
  await sandbox.commands.run(
    [
      "mkdir -p /home/sandbox/.pki/nssdb",
      "certutil -d sql:/home/sandbox/.pki/nssdb -N --empty-password || true",
      "certutil -d sql:/home/sandbox/.pki/nssdb -A -n opensandbox-proxy -t 'TC,C,T' -i /usr/local/share/ca-certificates/opensandbox-proxy.crt",
    ].join(" && "),
  );

  // Create the dir we've pointed TMPDIR at.
  await sandbox.commands.run("mkdir -p /home/sandbox/tmp && chmod 700 /home/sandbox/tmp");

  // Upload the latest server.ts fresh each launch — the snapshot only holds
  // the infrastructure (chromium, libretto, npm deps), not the app code.
  console.log("Uploading server.ts...");
  const serverSource = readFileSync("./server.ts", "utf8");
  await sandbox.files.write("/home/sandbox/server.ts", serverSource);

  // Start the server as a long-lived exec session so it isn't reaped when the
  // setup-command shells exit. Raising the hard nofiles limit needs root, so
  // wrap with sudo -E (preserves ANTHROPIC_API_KEY + TMPDIR). Everything Node
  // spawns — libretto, Chromium — inherits the higher ceiling.
  console.log("Starting in-sandbox server...");
  const server = await sandbox.exec.start("sudo", {
    args: [
      "-E",
      "bash", "-c",
      "ulimit -n 65535 && cd /home/sandbox && exec npx tsx /home/sandbox/server.ts",
    ],
    cwd: "/home/sandbox",
    onStdout: (b) => process.stdout.write(`[server] ${new TextDecoder().decode(b)}`),
    onStderr: (b) => process.stderr.write(`[server!] ${new TextDecoder().decode(b)}`),
  });

  // Poll until :3000 answers.
  let ready = false;
  for (let i = 0; i < 60; i++) {
    const { stdout } = await sandbox.commands.run(
      `curl -sS -o /dev/null -w '%{http_code}' http://localhost:${APP_PORT}/ || echo 000`,
    );
    if (stdout.trim() === "200") { ready = true; break; }
    await new Promise((r) => setTimeout(r, 1000));
  }
  if (!ready) {
    console.error("Server didn't answer on port 3000 within 60s — check [server] logs above.");
    await sandbox.kill();
    process.exit(1);
  }

  const url = `https://${sandbox.getPreviewDomain(APP_PORT)}`;
  console.log("\n────────────────────────────────────────────");
  console.log(`  ready: ${url}`);
  console.log("────────────────────────────────────────────");
  console.log("Press Ctrl-C to shut down.\n");

  const shutdown = async () => {
    console.log("\nShutting down...");
    try { server.close(); } catch { /* best effort */ }
    try { await sandbox.kill(); } catch { /* best effort */ }
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  await new Promise(() => { /* block forever */ });
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
